---
title: "bike_stuff"
author: "Joseph White"
date: "10/27/22"
output: github_document
---

```{r}
library(tidyverse) 
library(dsbox)
library(lubridate)
library(ggplot2)
```

```{r}
bike_data <- read_csv("202209-capitalbikeshare-tripdata.csv")
```

```{r}
bike_data_m <- bike_data %>%
  filter(member_casual == "member")

bike_data_c <- bike_data %>%
  filter(member_casual == "casual")

ggplot(bike_data_m, mapping = aes(x = start_lng, y = start_lat)) +
  geom_point()

ggplot(bike_data_c, mapping = aes(x = start_lng, y = start_lat)) +
  geom_point()
```
## bikes out per day ish
```{r}
time_bike = 1:1440
bikes_out = 1:1440
df_1 <- data.frame(time_bike,bikes_out)
bike_data_use <- bike_data %>% 
  select(started_at) %>%
  separate(started_at, c("date", "time"), " ") %>%
  separate(time, c("hour","minute","second"), ":") %>%
  mutate(minu = as.numeric(hour)*60 + as.numeric(minute))%>%
  separate(date, c("year","month","day"), "-") %>%
  filter(day == "01")
```


# plot
```{r}
ggplot(bike_data_use, aes(x= minu)) + geom_dotplot(binwidth = 5)
```

